### ISSUE TITLE
Compatability problems with Windows

### ISSUE THREAD

**Issue by InnocentusLime** [agerasev/uni-path#1]
# System configuration

**OS**: Windows 11 (however, it seems that the bug can be reproduced on any version of windows)

# What versions have this issue

All versions of `uni-path`.

# The issue

Paths that are considered "absolute" by Windows and Rust's stdlib aren't considered absolute by `uni-path`.

That causes `ocl-include` to behave incorrectly when it receives an absolute path to the file. For example [here](https://github.com/agerasev/ocl-include/blob/master/src/source/fs.rs#L89-L91) the code treats paths like "C:/Users/user/documents/some_file.txtl" as non-absolute and [starts looking for it inside other directories](https://github.com/agerasev/ocl-include/blob/master/src/source/fs.rs#L93-L103).

At the same time, it's not unrealistic to have paths like "C:/Users/user/documents/some_file.txt" get passed to the program.

# Code to reproduce the issue

```rust
fn main() {
    let path_str = "C:/Users/user/documents/some_file.txt";
    let std_path = std::path::Path::new(path_str);
    let uni_path = uni_path::Path::new(path_str);

    assert!(std_path.is_absolute()); // Doesn't panic
    assert!(uni_path.is_absolute()); // Panics
}
```

**Comment by agerasev** [comment]
This this is intended behavior of `uni-path`. It expects Unix-style paths on any platform.
```rust
fn main() {
    let path_str = "/home/user/documents/some_file.txt";
    let std_path = std::path::Path::new(path_str);
    let uni_path = uni_path::Path::new(path_str);

    assert!(uni_path.is_absolute()); // Never panics 
    assert!(std_path.is_absolute()); // Panics on non-Unix
}
```

**Comment by InnocentusLime** [comment]
Yes, that's true, but it ends up not working on Windows, because `ocl_include` fails to locate the file. That compromises the cross-platform aspect.

Unix style "absolute" paths aren't considered absolute on Windows too. They are considered to be "paths relative to the current drive".

It also brings in user-unfriendly behaviour. A program can receive ANY input. When someone gives a program, that uses `uni-path` or `ocl-include`, a path like `C:\Users\user\doc.txt` (which is, I reiterate, a completely normal path for a windows user, who doesn't know Linux), they receive an unhelpful error like "invalid volume name".

The API doesn't really abstract the path system that well anyway, since in the very end you have to give that path to the OS api without any changes, hoping it accepts it. Which, as I said, brings in a lot of "buts" on Windows, especially when the programm receives a path that starts with `\\?\` — the extended path prefix.

**Comment by InnocentusLime** [comment]
To add to the problem, even in Unix style the paths aren't cross-platform. Windows doesn't have a `home` directory at the root of `C:`. So `/home/user/` is an invalid path anyway.

**Comment by agerasev** [comment]
Yes, I agree, having to use Unix paths on non-Unix platforms is bad idea.
Honestly, I don't remember the reason why I decided to use `uni-path` (maybe to have platform-independent absolute paths for in-memory files). 

I've updated [`ocl-include`](https://crates.io/crates/ocl-include) to use `std::path`.

Thank you for your feedback!

**Comment by InnocentusLime** [comment]
I am closing this issue in that case 😄
